services:
  backend:
    build:
      context: ./api
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_URL: jdbc:postgresql://db:5432/match-my-movie
      DATABASE_USERNAME: match-my-movie
      DATABASE_PASSWORD: match-my-movie-pw
      API_KEY: ${API_KEY}
    depends_on:
      - db

  frontend:
    build:
      context: ./web
    container_name: react-app
    ports:
      - "3000:80"
    environment:
      REACT_APP_BACKEND_URL: http://188.245.178.94:8080
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: match-my-movie
      POSTGRES_PASSWORD: match-my-movie-pw
      POSTGRES_DB: match-my-movie
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
