name: Deploy to Hetzner

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - main  # Pas dit aan naar de branch die je wilt gebruiken

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_HOST: "188.245.178.94"       # Hetzner server IP
      SSH_USER: "root"             # Gebruikersnaam (meestal root)
      APP_DIR: "/var/www/MatchMyMovie"   # Locatie op de server

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Stel SSH-sleutel in
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

      # Maak het env.properties bestand met GitHub Secrets
      - name: Create env.properties from secrets
        run: |
          echo "TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" > api/src/main/resources/env.properties
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> api/src/main/resources/env.properties
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> api/src/main/resources/env.properties
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> api/src/main/resources/env.properties
        shell: bash

      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ${{ github.workspace }}
          host: ${{ secrets.SSH_HOST }}
          remote: ${{ secrets.APP_DIR }}
          port: 22
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          
        # SSH into server en run docker compose
#      - name: SSH into server and run Docker Compose
#        run: |
#            ssh ${{ secrets.DEPLOY_SSH_KEY }} $SSH_USER@$SSH_HOST << 'EOF'
#              cd $APP_DIR
#              docker-compose down || true    # Stop bestaande containers
#              docker-compose build           # Bouw de nieuwe containers
#              docker-compose up -d           # Start de containers in detached mode
#            EOF
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /var/www/MatchMyMovie/workspace
            ls -al
            docker compose down || true    # Stop bestaande containers
            docker compose build           # Bouw de nieuwe containers
            docker compose up -d           # Start de containers in detached mode

