name: Deploy to Hetzner

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - main  # Pas dit aan naar de branch die je wilt gebruiken

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_HOST: "188.245.178.94"       # Hetzner server IP
      SSH_USER: "root"             # Gebruikersnaam (meestal root)
      APP_DIR: "/var/www/MatchMyMovie"   # Locatie op de server

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Stel SSH-sleutel in
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

#      # Upload files
#      - name: Upload files
#        run: |
#          scp -r . $SSH_USER@$SSH_HOST:$APP_DIR

      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: .
          host: ${{ secrets.SSH_HOST }}
          remote: ${{ secrets.APP_DIR }}
          port: 22
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          
        # SSH into server en run docker compose
      - name: SSH into server and run Docker Compose
        run: |
            ssh $SSH_USER@$SSH_HOST << 'EOF'
              cd $APP_DIR
              docker-compose down || true    # Stop bestaande containers
              docker-compose build           # Bouw de nieuwe containers
              docker-compose up -d           # Start de containers in detached mode
            EOF

          
